[package]
name = "waql-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
egui = "0.33.2"
egui_code_editor = { git = "https://github.com/xmimu/egui_code_editor.git", branch = "waql-tool" }
serde_json = "1.0.145"
ureq = { version = "3.1.4", features = ["json"] }
